POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "아우터상품-7",
  "brandId": 1,
  "price": 56000,
  "categoryInfoRequest": {
    "firstLayerCategory" : "MEN",
    "secondLayerCategory" : "OUTER",
    "thirdLayerCategory" : "BLOUSON_MA1",
    "inferiorLayerCategory" : null
  },
  "couponApplyPossible": "POSSIBLE",
  "discountApplyPossible": "POSSIBLE",
  "discountMinRate": 0,
  "discountMaxRate": 20,
  "outboundPossibleDay": 3,
  "productSizeRequests": [
    {
      "sizeName": "S",
      "totalLength": "64",
      "shoulder": "50.5",
      "chest": "57",
      "sleeve": "59",
      "waist": "",
      "crotch": "",
      "hip": "",
      "thigh": "",
      "hem": "",
      "width": "",
      "height": "",
      "depth": "",
      "productSizeType": "OUTER"
    },
    {
      "sizeName": "M",
      "totalLength": "66",
      "shoulder": "52.5",
      "chest": "59",
      "sleeve": "61",
      "waist": "",
      "crotch": "",
      "hip": "",
      "thigh": "",
      "hem": "",
      "width": "",
      "height": "",
      "depth": "",
      "productSizeType": "OUTER"
    },
    {
      "sizeName": "L",
      "totalLength": "68",
      "shoulder": "54.5",
      "chest": "61",
      "sleeve": "63",
      "waist": "",
      "crotch": "",
      "hip": "",
      "thigh": "",
      "hem": "",
      "width": "",
      "height": "",
      "depth": "",
      "productSizeType": "OUTER"
    }
  ],
  "thumbnailLink": "http://knit1-thumbnail.com",
  "profileImagesLink": ["http://knit1-prifile.com"],
  "detailImageLink": ["http://knit1-detail.com"],
  "skuProductRequests": [
    {
      "name": "니트1 - 사이즈1",
      "stock": 0,
      "plusPrice": 3000,
      "productStatus": "TEMP"
    }
  ],
  "productType": "CLOTHES"
}

