POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "[포터리] 코트상품-1",
  "brandId": 2,
  "price": 56000,
  "categoryInfoRequest": {
    "firstLayerCategory" : "MEN",
    "secondLayerCategory" : "OUTER",
    "thirdLayerCategory" : "WINTER_DOUBLE_COAT",
    "inferiorLayerCategory" : null
  },
  "couponApplyPossible": "POSSIBLE",
  "discountApplyPossible": "POSSIBLE",
  "discountMinRate": 0,
  "discountMaxRate": 20,
  "outboundPossibleDay": 3,
  "productSizeRequests": [
    {
      "sizeName": "S",
      "totalLength": "117",
      "shoulder": "60.5",
      "chest": "61",
      "sleeve": "70",
      "waist": "",
      "crotch": "",
      "hip": "",
      "thigh": "",
      "hem": "",
      "width": "",
      "height": "",
      "depth": "",
      "productSizeType": "OUTER"
    },
    {
      "sizeName": "M",
      "totalLength": "119",
      "shoulder": "62",
      "chest": "63",
      "sleeve": "72",
      "waist": "",
      "crotch": "",
      "hip": "",
      "thigh": "",
      "hem": "",
      "width": "",
      "height": "",
      "depth": "",
      "productSizeType": "OUTER"
    },
    {
      "sizeName": "L",
      "totalLength": "121",
      "shoulder": "63.5",
      "chest": "65",
      "sleeve": "73",
      "waist": "",
      "crotch": "",
      "hip": "",
      "thigh": "",
      "hem": "",
      "width": "",
      "height": "",
      "depth": "",
      "productSizeType": "OUTER"
    }
  ],
  "thumbnailLink": "http://knit1-thumbnail.com",
  "profileImagesLink": ["http://knit1-prifile.com"],
  "detailImageLink": ["http://knit1-detail.com"],
  "skuProductRequests": [
    {
      "name": "[포터리] 코트1 - 사이즈S",
      "stock": 0,
      "plusPrice": 3000,
      "productStatus": "TEMP"
    },
    {
      "name": "[포터리] 코트1 - 사이즈M",
      "stock": 0,
      "plusPrice": 5000,
      "productStatus": "TEMP"
    },
    {
      "name": "[포터리] 코트1 - 사이즈L",
      "stock": 0,
      "plusPrice": 7000,
      "productStatus": "TEMP"
    }
  ],
  "productType": "CLOTHES"
}

