GET http://localhost:8080/products/1
Content-Type: application/json

{
  "statusCode": "OK",
  "message": null,
  "result": {
    "productResponse": {
      "productId": 1,
      "name": "아우터상품-1",
      "price": 56000,
      "outboundPossibleDay": 4,
      "deliveryFee": "NOT_FREE",
      "couponApplyPossible": "POSSIBLE",
      "discountApplyPossible": "POSSIBLE",
      "discountMinRate": 0,
      "discountMaxRate": 20,
      "productStatus": "TEMP",
      "productCreatedDate": null,
      "productUpdatedDate": null
    },
    "categoryResponse": {
      "firstLayerCategory": "MEN",
      "secondLayerCategory": "OUTER",
      "thirdLayerCategory": "BLOUSON_MA1"
    },
    "brandResponse": {
      "brandId": 1,
      "brandName": "COS",
      "corporateNumber": "11-11-11-14",
      "communicationSellingNumber": "031-078-1114",
      "representative": "대표 사업자4",
      "location": "서울특별시 강남구 개쩌는동1"
    },
    "skuProductResList": [
      {
        "id": 1,
        "productId": 1,
        "name": "니트1 - 사이즈1",
        "stock": 0,
        "plusPrice": 3000.0,
        "skuProductStatus": null,
        "createdDate": "2024-12-25T00:39:14.991079",
        "updatedDate": "2024-12-25T00:39:14.991113"
      }
    ],
    "sizeResList": [
      {
        "id": 1,
        "productId": 1,
        "sizeName": null,
        "totalLength": "64",
        "shoulder": "50.5",
        "chest": "57",
        "sleeve": "59",
        "waist": null,
        "crotch": null,
        "hip": null,
        "thigh": null,
        "hem": null,
        "width": null,
        "height": null,
        "depth": null,
        "productSizeType": null,
        "createdDate": "2024-12-25T00:39:15.003995",
        "updatedDate": "2024-12-25T00:39:15.004009"
      },
      {
        "id": 2,
        "productId": 1,
        "sizeName": null,
        "totalLength": "66",
        "shoulder": "52.5",
        "chest": "59",
        "sleeve": "61",
        "waist": null,
        "crotch": null,
        "hip": null,
        "thigh": null,
        "hem": null,
        "width": null,
        "height": null,
        "depth": null,
        "productSizeType": null,
        "createdDate": "2024-12-25T00:39:15.004022",
        "updatedDate": "2024-12-25T00:39:15.004024"
      },
      {
        "id": 3,
        "productId": 1,
        "sizeName": null,
        "totalLength": "68",
        "shoulder": "54.5",
        "chest": "61",
        "sleeve": "63",
        "waist": null,
        "crotch": null,
        "hip": null,
        "thigh": null,
        "hem": null,
        "width": null,
        "height": null,
        "depth": null,
        "productSizeType": null,
        "createdDate": "2024-12-25T00:39:15.004028",
        "updatedDate": "2024-12-25T00:39:15.004031"
      }
    ],
    "productImageResList": [
      {
        "id": 1,
        "productId": 1,
        "imageUrl": "http://knit1-thumbnail.com",
        "imageType": "THUMBNAIL",
        "createdDate": "2024-12-25T00:39:15.006921",
        "updatedDate": "2024-12-25T00:39:15.006933"
      },
      {
        "id": 2,
        "productId": 1,
        "imageUrl": "http://knit1-prifile.com",
        "imageType": "PROFILE",
        "createdDate": "2024-12-25T00:39:15.006941",
        "updatedDate": "2024-12-25T00:39:15.00695"
      },
      {
        "id": 3,
        "productId": 1,
        "imageUrl": "http://knit1-detail.com",
        "imageType": "DETAIL",
        "createdDate": "2024-12-25T00:39:15.006953",
        "updatedDate": "2024-12-25T00:39:15.006956"
      }
    ]
  }
}

//Response code: 200; Time: 194ms; Content length: 2330 bytes